Importing Pandas

In [1]:
import pandas as pd

Example DataFrame

In [2]:
data = {
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25, 30, 35],
    'Country' : ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

Loading a DataFrame

In [3]:
df = pd.read_csv('orders.csv')

Exploring a Data Frame

In [4]:
df.head()  #First 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [5]:
df.tail()   #Last 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [6]:
df.info()   # Column types and non-null values

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [7]:
df.describe()  # Summary stats

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [8]:
df.columns   # Column Names

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [9]:
df.index   #Row indices

RangeIndex(start=0, stop=40, step=1)

Accessing & Filtering Data

Basic Access

In [10]:
df['Product']   #Single Column

0                    Laptop
1                Headphones
2              Office Chair
3                 Desk Lamp
4                  Keyboard
5                  Notebook
6             Standing Desk
7                   Monitor
8                       Pen
9                     Mouse
10                   Webcam
11             File Cabinet
12                  Stapler
13                USB Drive
14                Bookshelf
15            Printer Paper
16           Wireless Mouse
17           Desk Organizer
18               Calculator
19               Whiteboard
20             Highlighters
21        Bluetooth Speaker
22             Office Plant
23             Sticky Notes
24             Tablet Stand
25           Paper Shredder
26           Desk Chair Mat
27             Binder Clips
28        Wireless Keyboard
29            Desk Calendar
30                  USB Hub
31         Document Scanner
32    Desk Drawer Organizer
33              Index Cards
34            Monitor Stand
35       Desk Lamp with USB
36         Wireless Earbuds
37                 Desk Pad
38              Power Strip
39               Desk Clock
Name: Product, dtype: str

In [11]:
df[['CustomerName', 'Product']]   #Multiple Column

        CustomerName                Product
0         John Smith                 Laptop
1          Sarah Lee             Headphones
2           Ali Khan           Office Chair
3         Alice Wong              Desk Lamp
4      Carlos Mendez               Keyboard
5       Nora Ibrahim               Notebook
6        Emily Davis          Standing Desk
7         James Park                Monitor
8        Maria Rossi                    Pen
9   Takeshi Nakamura                  Mouse
10     Sophie Martin                 Webcam
11         Raj Patel           File Cabinet
12       Emma Wilson                Stapler
13   Diego Rodriguez              USB Drive
14         Lisa Chen              Bookshelf
15      Ahmed Hassan          Printer Paper
16     Anna Kowalski         Wireless Mouse
17     Michael Brown         Desk Organizer
18       Yuki Tanaka             Calculator
19   Fatima Al-Zahra             Whiteboard
20    David Thompson           Highlighters
21    Isabella Silva      Bluetooth Speaker
22    Oliver Schmidt           Office Plant
23        Zara Ahmed           Sticky Notes
24    Lucas Anderson           Tablet Stand
25      Chloe Dubois         Paper Shredder
26     Miguel Torres         Desk Chair Mat
27       Nina Petrov           Binder Clips
28      Seo-yeon Kim      Wireless Keyboard
29   Giuseppe Romano          Desk Calendar
30      Amira Hassan                USB Hub
31     Thomas Müller       Document Scanner
32   Sofia Rodriguez  Desk Drawer Organizer
33      Alex Johnson            Index Cards
34     Yuki Yamamoto          Monitor Stand
35     Emma Thompson     Desk Lamp with USB
36     Carlos Santos       Wireless Earbuds
37    Leila Mansouri               Desk Pad
38        Daniel Kim            Power Strip
39      Anna Ivanova             Desk Clock

In [12]:
df.iloc[0]   #First row by position

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [13]:
df.loc[df['CustomerName'] == 'John Smith']   #bring column by Customer Name

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

Conditional Filtering (Boolean masks)

In [14]:
df[df['Quantity']>5]   #Quantity over 5

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [15]:
df[df['Country'] == 'USA']   # Country Match

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [16]:
df[(df['Quantity']==1) & (df['Country'] == 'UK')]   #Multiple Conditions

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

Advanced Filtering

In [17]:
df[df['CustomerName'].str.startswith('A')]         # Names starting with A

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [18]:
df[df['Country'].isin(['USA', 'UK'])]      # Match multiple values

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

In [19]:
df[~df['Country'].isin(['USA'])]        # NOT condition

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

CRUD Operations in pandas

Create (Insert Rows)

In [21]:
new_row = pd.DataFrame([{'OrderID' : 1041, 'CustomerName' : 'Bala', 'Product' : 'Webcam', 'Category' : 
                         'Electronics', 'Quantity' : 1, 'Price' : 150.0, 'OrderDate' : '2024-08-11', 'Shipped' : 'Yes', 'Country' : 'India'}])
df = pd.concat([df, new_row], ignore_index=True)

In [29]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,UKRAINE
40,1041,Bala,Webcam,Electronics,1,300.0,2024-08-11,Yes,INDIA

Read (Access Data)

In [24]:
df.loc[df['CustomerName'] == 'Bala']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
40,1041,Bala,Webcam,Electronics,1,150.0,2024-08-11,Yes,India

In [25]:
df.iloc[40]

OrderID                1041
CustomerName           Bala
Product              Webcam
Category        Electronics
Quantity                  1
Price                 150.0
OrderDate        2024-08-11
Shipped                 Yes
Country               India
Name: 40, dtype: object

Update (Modify Values)

In [26]:
df.loc[df['CustomerName'] == 'Bala', 'Price'] = 300.0

In [28]:
df['Country'] = df['Country'].str.upper()

Delete (Drop Data)

In [ ]:
df = df.drop(2, axis=0)                             # Drop row with index 2
df = df[df['Name'] != 'Alice']                      # Drop rows where name == Alice
df = df.drop('Age', axis=1)                         # Drop 'Age' column

Cleaning Data

In [ ]:
df.isnull().sum()                          # Count missing values
df.dropna(inplace=True)                   # Drop rows with missing values
df.fillna({'Age': 0}, inplace=True)       # Fill missing Age values with 0
df.rename(columns={'Age': 'Years'}, inplace=True)   # Rename column
df['Years'] = df['Years'].astype(float)   # Convert column to float

Analysing Data

In [ ]:
df['Country'].value_counts()                       # Count occurrences
df.groupby('Country')['Age'].mean()                # Average age per country
df.sort_values(by='Age', ascending=False)          # Sort by Age descending

Saving Data

In [ ]:
df.to_csv('cleaned_data.csv', index=False)
df.to_excel('output.xlsx', index=False)